### ISSUE TITLE
Error when running for the first time

### ISSUE THREAD

**Issue by catsclaw** [akalongman/sublimetext-codeformatter#208]
I get the following error when I run for the first time:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\Chris\AppData\Roaming\Sublime Text 3\Packages\CodeFormatter\CodeFormatter.py", line 79, in run
    formatter = Formatter(self.view, file_name, syntax, saving)
  File "C:\Users\Chris\AppData\Roaming\Sublime Text 3\Packages\CodeFormatter\codeformatter\formatter.py", line 59, in __init__
    if ("syntaxes" in opts and opts["syntaxes"]):
TypeError: argument of type 'NoneType' is not iterable

**Comment by akalongman** [comment]
I will check. Thank you for submitting

**Comment by akalongman** [comment]
Can you show me your CF settings?

**Comment by ticapix** [comment]
I have the same error. What is CF ?

**Comment by catsclaw** [comment]
CodeFormatter. I'm not by my home computer atm, so I can't send over my settings yet.

**Comment by ticapix** [comment]
this the content of CodeFormatter.sublime-settings http://pastebin.com/LnDgddVv

**Comment by ticapix** [comment]
solved by restarting Sublime. All good. (and re-verified by uninstalling/install it)

**Comment by catsclaw** [comment]
I tried restarting, but it didn't fix my problem.

**Comment by examinedliving** [comment]
As @catsclaw, restarting didn't fix this for me.  Windows 7 64bit
